# base image
ARG CONTAINER_BASE_IMAGE_NAME=ubuntu
ARG CONTAINER_BASE_IMAGE_TAG=26.04
FROM ${CONTAINER_BASE_IMAGE_NAME}:${CONTAINER_BASE_IMAGE_TAG}

# timezone
ENV TZ="Etc/UTC"

# set locale
ENV LANG=C.UTF-8
ENV LC_ALL=C.UTF-8

ARG DEBIAN_FRONTEND=noninteractive
RUN rm -f /etc/apt/apt.conf.d/docker-clean

# install apt packages and dependencies
RUN --mount=type=cache,target=/var/cache/apt \
    apt-get update && \
    apt-get install -y --no-install-recommends \
    git make curl gnupg2 wget ca-certificates openssh-client \
    sudo \
    shellcheck \
    # cpp
    clang \
    # vcpkg
    curl zip unzip tar pkg-config

# default user
ARG USERNAME=devcontainer
ARG USER_UID=1000
ARG USER_GID=1000
# add $USER to usergroup
# Some variants of Ubuntu has default user ubuntu with 1000:1000
# Delete default user if USER_UID:USER_GID is already present
RUN OLD_USER="$(getent passwd ${USER_UID} | cut -d: -f1 || true)"; \
    if [ -n "$OLD_USER" ]; then \
    userdel -r "$OLD_USER" || true; \
    fi; \
    groupadd --gid ${USER_GID} ${USERNAME} && \
    useradd --uid ${USER_UID} --gid ${USER_GID} -m -l ${USERNAME} -s /bin/bash && \
    usermod -aG sudo ${USERNAME} && \
    echo "${USERNAME}:${USERNAME}_super_user" | chpasswd

# install cuda-keyring
COPY scripts/install_cuda_keyring.sh /tmp/install_cuda_keyring.sh
RUN bash /tmp/install_cuda_keyring.sh \
    && rm /tmp/install_cuda_keyring.sh

# Install required components from CUDA toolkit
ARG __CUDA_TOOLKIT_VER=13-3
ARG __NSIGHT_SYSTEMS_CLI_VER=2026.3.1
RUN --mount=type=cache,target=/var/cache/apt \
    apt-get update && \
    apt-get install -y --no-install-recommends \
    cuda-nvcc-${__CUDA_TOOLKIT_VER} \
    cuda-gdb-${__CUDA_TOOLKIT_VER} \
    cuda-nsight-compute-${__CUDA_TOOLKIT_VER} \
    nsight-systems-cli-${__NSIGHT_SYSTEMS_CLI_VER} && \
    rm -f /etc/apt/apt.conf.d/docker-clean

ENV PATH="$PATH:/usr/local/cuda/bin"

USER ${USERNAME}

# install CMake (non-root)
# renovate: datasource=github-tags depName=Kitware/CMake versioning=loose
ARG CMAKE_VERSION=4.3.3
RUN --mount=type=bind,source=scripts/install_cmake.sh,target=/tmp/install_cmake.sh,readonly \
    CMAKE_VERSION=${CMAKE_VERSION} /tmp/install_cmake.sh /home/${USERNAME}/cmake
ENV PATH="$PATH:/home/${USERNAME}/cmake/bin/"

# install vcpkg (non-root)
# renovate: datasource=github-tags depName=microsoft/vcpkg versioning=loose
ARG VCPKG_VERSION=2026.06.24
RUN --mount=type=bind,source=scripts/install_vcpkg.sh,target=/tmp/install_vcpkg.sh,readonly \
    VCPKG_VERSION=${VCPKG_VERSION} /tmp/install_vcpkg.sh /home/${USERNAME}
ENV PATH="$PATH:/home/${USERNAME}/vcpkg/"
ENV VCPKG_ROOT=/home/${USERNAME}/vcpkg/

# working directory
ARG __REPOSITORY_NAME=cuda_cpp_learning
WORKDIR /${__REPOSITORY_NAME}

# entry point
ENTRYPOINT ["/bin/bash"]