name: Publish NuGet Packages

on:
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Restore Docker build cache
        uses: actions/cache@v4
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.ref }}-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-${{ github.ref }}-
            ${{ runner.os }}-buildx-

      - name: Get user IDs
        id: user
        run: |
          echo "uid=$(id -u)" >> "$GITHUB_OUTPUT"
          echo "gid=$(id -g)" >> "$GITHUB_OUTPUT"

      - name: Build Container
        uses: docker/build-push-action@v6
        with:
          context: .
          file: .devcontainer/Containerfile
          tags: vcpkg-nuget-publisher:latest
          load: true
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new,mode=max
          target: base
          secrets: |
            vcpkg-nuget-secret=${{ secrets.VCPKG_NUGET_RW }}
          build-args: |
            USERNAME=devcontainer
            USER_UID=${{ steps.user.outputs.uid }}
            USER_GID=${{ steps.user.outputs.gid }}
            CACHE_BUST="${{ github.run_id }}"

      - name: Update Docker cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache

      - name: Build and Publish packages
        run: |
          docker run --rm \
            --user "${{ steps.user.outputs.uid }}:${{ steps.user.outputs.gid }}" \
            --entrypoint /bin/bash \
            -e VCPKG_BINARY_SOURCES="clear;nuget,https://nuget.pkg.github.com/mitul93/index.json,readwrite" \
            -v "${{ github.workspace }}:/workspace" \
            -w /workspace \
            vcpkg-nuget-publisher \
            -c 'make publish_nuget_packages'